### ISSUE TITLE
更新列表的时候报错

### ISSUE THREAD

**Issue by Landius** [SolomonLeon/netease-music-downloader#4]
```bash
$ main.py -a playlist1 playlist2
...
$ main.py -rn playlist2
...
$ main.py -u # 删除某个歌单后执行更新
---------- Updating all playlists ----------
[*] Playlist name: 下载
 |  Removing deleted songs...
Traceback (most recent call last):
  File "main.py", line 394, in <module>
    updateAllPlaylist()
  File "main.py", line 325, in updateAllPlaylist
    removePlaylistInSongDB(delDataList)
TypeError: removePlaylistInSongDB() missing 1 required positional argument: 'dataList'
```
貌似少了个参数 `playlist.name`?

**Comment by leonsama** [comment]
是的，我现在正在写GUI，到时候一并更新
