### ISSUE TITLE
添加歌单时出错

### ISSUE THREAD

**Issue by l0o0** [SolomonLeon/netease-music-downloader#5]
win10 系统，从github下载了代码后，安装了所要的模块。运行时出现错误

```python
λ python main.py -a 9646415
Traceback (most recent call last):
  File "main.py", line 392, in <module>
    addPlaylist(args.addPlaylist[0])
  File "main.py", line 24, in addPlaylist
    playlistResq = getPlaylist(playlistNid)
  File "D:\workspace\netease-music-downloader\api.py", line 16, in getPlaylist
    response = requests.request("GET", url, headers=headers).json()
  File "D:\anaconda3\lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "D:\anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "D:\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

看api.py 里那个接口地址好像返回不了东西。

**Comment by ozzxzzo** [comment]
同样的问题
